# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5c89ab05fc294ac540cf273983be438b4a14a93d03f981d9ce4cd3061c74e5b4d6005516bb1faa69fe30211018f941273c6926141b6bf110c9e52bc398446f2

test:
  secret_key_base: c95f0e9716aa55af35dda8eb27cad694692dd5e60dcf920f2f02abc4d287a45401f1bad8da8f06ba8788534ff364b604215db4b1c2f1a8544540a8c89ab7221d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
